2013/11/14 16:44:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "tbluser".' in /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CController.php:483
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CController.php(270): CController->missingAction('tbluser')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CWebApplication.php(282): CController->run('tbluser')
#2 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CWebApplication.php(141): CWebApplication->runController('site/tbluser')
#3 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/yii-new/testdrive/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii-new/testdrive/index.php?r=site/tbluser
HTTP_REFERER=http://localhost/yii-new/testdrive/index.php?r=site/login
---
2013/11/14 16:44:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "tbluser".' in /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CController.php:483
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CController.php(270): CController->missingAction('tbluser')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CWebApplication.php(282): CController->run('tbluser')
#2 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CWebApplication.php(141): CWebApplication->runController('site/tbluser')
#3 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/yii-new/testdrive/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii-new/testdrive/index.php?r=site/tbluser
HTTP_REFERER=http://localhost/yii-new/testdrive/index.php?r=site/login
---
2013/11/14 16:44:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "tblUser".' in /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CController.php:483
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CController.php(270): CController->missingAction('tblUser')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CWebApplication.php(282): CController->run('tblUser')
#2 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CWebApplication.php(141): CWebApplication->runController('site/tblUser')
#3 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/yii-new/testdrive/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii-new/testdrive/index.php?r=site/tblUser
HTTP_REFERER=http://localhost/yii-new/testdrive/index.php?r=site/tbluser
---
2013/11/14 16:44:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "tblUser".' in /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CController.php:483
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CController.php(270): CController->missingAction('tblUser')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CWebApplication.php(282): CController->run('tblUser')
#2 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CWebApplication.php(141): CWebApplication->runController('site/tblUser')
#3 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/yii-new/testdrive/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii-new/testdrive/index.php?r=site/tblUser
HTTP_REFERER=http://localhost/yii-new/testdrive/index.php?r=site/tblUser
---
2013/11/15 14:37:47 [error] [system.db.CDbCommand] Error in preparing SQL: PRAGMA table_info('public'.'tbl_word')
in /Applications/XAMPP/xamppfiles/htdocs/yii-new/testdrive/index.php (13)
2013/11/15 14:37:47 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: CDbCommand failed to prepare the SQL statement: SQLSTATE[HY000]: General error: 1 near ".": syntax error. The SQL statement executed was: PRAGMA table_info('public'.'tbl_word').
in /Applications/XAMPP/xamppfiles/htdocs/yii-new/testdrive/index.php (13)
2013/11/15 14:37:47 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: CDbCommand failed to prepare the SQL statement: SQLSTATE[HY000]: General error: 1 near ".": syntax error. The SQL statement executed was: PRAGMA table_info('public'.'tbl_word')' in /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/db/CDbCommand.php:543
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/db/CDbCommand.php(396): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/db/schema/sqlite/CSqliteSchema.php(132): CDbCommand->queryAll()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/db/schema/sqlite/CSqliteSchema.php(115): CSqliteSchema->findColumns(Object(CDbTableSchema))
#3 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/db/schema/CDbSchema.php(103): CSqliteSchema->loadTable('public.tbl_word')
#4 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/gii/generators/model/ModelCode.php(195): CDbSchema->getTable('public.tbl_word', false)
#5 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/gii/generators/model/ModelCode.php(147): ModelCode->getTableSchema('public.tbl_word')
#6 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/validators/CInlineValidator.php(42): ModelCode->validateTableName('tableName', Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/validators/CValidator.php(213): CInlineValidator->validateAttribute(Object(ModelCode), 'tableName')
#8 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/base/CModel.php(159): CValidator->validate(Object(ModelCode), NULL)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/gii/CCodeGenerator.php(159): CModel->validate()
#10 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#11 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#13 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#14 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#15 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CWebApplication.php(282): CController->run('index')
#16 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#17 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/base/CApplication.php(180): CWebApplication->processRequest()
#18 /Applications/XAMPP/xamppfiles/htdocs/yii-new/testdrive/index.php(13): CApplication->run()
#19 {main}
REQUEST_URI=/yii-new/testdrive/index.php?r=gii/model/index
HTTP_REFERER=http://localhost/yii-new/testdrive/index.php?r=gii/model/index
---
2013/11/15 14:42:52 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[42000] [1049] Unknown database 'testdrive'' in /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/db/CDbConnection.php:382
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/base/CModule.php(387): CDbConnection->init()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CFormModel.php(39): ModelCode->init()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CWebApplication.php(282): CController->run('index')
#13 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /Applications/XAMPP/xamppfiles/htdocs/yii-new/testdrive/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii-new/testdrive/index.php?r=gii/model/index
HTTP_REFERER=http://localhost/yii-new/testdrive/index.php?r=gii/form/index
---
2013/11/17 14:46:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "testace".' in /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CController.php:483
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CController.php(270): CController->missingAction('testace')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CWebApplication.php(282): CController->run('testace')
#2 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CWebApplication.php(141): CWebApplication->runController('word/testace')
#3 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/yii-new/testdrive/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii-new/testdrive/index.php?r=word/testace
---
2013/11/17 14:46:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "ace".' in /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CController.php:483
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CController.php(270): CController->missingAction('ace')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CWebApplication.php(282): CController->run('ace')
#2 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CWebApplication.php(141): CWebApplication->runController('word/ace')
#3 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/yii-new/testdrive/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii-new/testdrive/index.php?r=word/ace
---
2013/11/17 14:46:52 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/auth/CAccessControlFilter.php:182
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/auth/CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/filters/CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CController.php(291): CFilterChain->run()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CWebApplication.php(282): CController->run('ace')
#8 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CWebApplication.php(141): CWebApplication->runController('word/ace')
#9 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/base/CApplication.php(180): CWebApplication->processRequest()
#10 /Applications/XAMPP/xamppfiles/htdocs/yii-new/testdrive/index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/yii-new/testdrive/index.php?r=word/ace
---
2013/11/17 14:47:08 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/auth/CAccessControlFilter.php:182
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/auth/CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/filters/CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CController.php(291): CFilterChain->run()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CWebApplication.php(282): CController->run('Ace')
#8 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CWebApplication.php(141): CWebApplication->runController('word/Ace')
#9 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/base/CApplication.php(180): CWebApplication->processRequest()
#10 /Applications/XAMPP/xamppfiles/htdocs/yii-new/testdrive/index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/yii-new/testdrive/index.php?r=word/Ace
---
2013/11/17 14:47:22 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/auth/CAccessControlFilter.php:182
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/auth/CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/filters/CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CController.php(291): CFilterChain->run()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CWebApplication.php(282): CController->run('ace')
#8 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CWebApplication.php(141): CWebApplication->runController('word/ace')
#9 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/base/CApplication.php(180): CWebApplication->processRequest()
#10 /Applications/XAMPP/xamppfiles/htdocs/yii-new/testdrive/index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/yii-new/testdrive/index.php?r=word/ace
---
2013/11/17 14:47:47 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/auth/CAccessControlFilter.php:182
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/auth/CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/filters/CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CController.php(291): CFilterChain->run()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CWebApplication.php(282): CController->run('ace')
#8 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CWebApplication.php(141): CWebApplication->runController('word/ace')
#9 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/base/CApplication.php(180): CWebApplication->processRequest()
#10 /Applications/XAMPP/xamppfiles/htdocs/yii-new/testdrive/index-test.php(15): CApplication->run()
#11 {main}
REQUEST_URI=/yii-new/testdrive/index-test.php?r=word/ace
---
2013/11/17 14:49:25 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/auth/CAccessControlFilter.php:182
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/auth/CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/filters/CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CController.php(291): CFilterChain->run()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CWebApplication.php(282): CController->run('ace')
#8 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CWebApplication.php(141): CWebApplication->runController('word/ace')
#9 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/base/CApplication.php(180): CWebApplication->processRequest()
#10 /Applications/XAMPP/xamppfiles/htdocs/yii-new/testdrive/index-test.php(15): CApplication->run()
#11 {main}
REQUEST_URI=/yii-new/testdrive/index-test.php?r=word/ace
---
2013/11/17 14:49:26 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/auth/CAccessControlFilter.php:182
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/auth/CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/filters/CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CController.php(291): CFilterChain->run()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CWebApplication.php(282): CController->run('ace')
#8 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CWebApplication.php(141): CWebApplication->runController('word/ace')
#9 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/base/CApplication.php(180): CWebApplication->processRequest()
#10 /Applications/XAMPP/xamppfiles/htdocs/yii-new/testdrive/index-test.php(15): CApplication->run()
#11 {main}
REQUEST_URI=/yii-new/testdrive/index-test.php?r=word/ace
---
2013/11/17 15:41:01 [error] [exception.CException] exception 'CException' with message 'Property "CMenu.activeItemCssClass" is not defined.' in /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/base/CComponent.php:173
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CWidgetFactory.php(161): CComponent->__set('activeItemCssCl...', 'green')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CBaseController.php(146): CWidgetFactory->createWidget(Object(TblUserController), 'zii.widgets.CMe...', Array)
#2 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CBaseController.php(172): CBaseController->createWidget('zii.widgets.CMe...', Array)
#3 /Applications/XAMPP/xamppfiles/htdocs/yii-new/testdrive/protected/views/layouts/main.php(112): CBaseController->widget('zii.widgets.CMe...', Array)
#4 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CBaseController.php(126): require('/Applications/X...')
#5 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CBaseController.php(95): CBaseController->renderInternal('/Applications/X...', Array, true)
#6 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/widgets/CContentDecorator.php(76): CBaseController->renderFile('/Applications/X...', Array, true)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/widgets/CContentDecorator.php(54): CContentDecorator->decorate('<div class="spa...')
#8 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/widgets/COutputProcessor.php(44): CContentDecorator->processOutput('<div class="spa...')
#9 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CBaseController.php(206): COutputProcessor->run()
#10 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CBaseController.php(300): CBaseController->endWidget('CContentDecorat...')
#11 /Applications/XAMPP/xamppfiles/htdocs/yii-new/testdrive/protected/views/layouts/column2.php(23): CBaseController->endContent()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CBaseController.php(126): require('/Applications/X...')
#13 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CBaseController.php(95): CBaseController->renderInternal('/Applications/X...', Array, true)
#14 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CController.php(784): CBaseController->renderFile('/Applications/X...', Array, true)
#15 /Applications/XAMPP/xamppfiles/htdocs/yii-new/testdrive/protected/controllers/TblUserController.php(128): CController->render('index', Array)
#16 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/actions/CInlineAction.php(49): TblUserController->actionIndex()
#17 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#18 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/filters/CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#19 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/filters/CFilter.php(40): CFilterChain->run()
#20 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#21 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#22 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#23 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CController.php(291): CFilterChain->run()
#24 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#25 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CWebApplication.php(282): CController->run('')
#26 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CWebApplication.php(141): CWebApplication->runController('tblUser')
#27 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/base/CApplication.php(180): CWebApplication->processRequest()
#28 /Applications/XAMPP/xamppfiles/htdocs/yii-new/testdrive/index-test.php(15): CApplication->run()
#29 {main}
REQUEST_URI=/yii-new/testdrive/index-test.php?r=tblUser
HTTP_REFERER=http://localhost/yii-new/testdrive/index-test.php?r=word
---
2013/11/17 16:21:26 [error] [php] Invalid argument supplied for foreach() (/Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/zii/widgets/CMenu.php:263)
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CBaseController.php(172): TblUserController->createWidget()
#1 /Applications/XAMPP/xamppfiles/htdocs/yii-new/testdrive/protected/views/layouts/column2.php(46): TblUserController->widget()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CBaseController.php(126): require()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CBaseController.php(95): TblUserController->renderInternal()
#4 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CController.php(784): TblUserController->renderFile()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii-new/testdrive/protected/controllers/TblUserController.php(128): TblUserController->render()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/actions/CInlineAction.php(49): TblUserController->actionIndex()
#7 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CController.php(308): CInlineAction->runWithParams()
#8 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/filters/CFilterChain.php(133): TblUserController->runAction()
#9 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/filters/CFilter.php(40): CFilterChain->run()
#10 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CController.php(1145): CAccessControlFilter->filter()
#11 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/filters/CInlineFilter.php(58): TblUserController->filterAccessControl()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter()
#13 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CController.php(291): CFilterChain->run()
#14 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CController.php(265): TblUserController->runActionWithFilters()
#15 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CWebApplication.php(282): TblUserController->run()
#16 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CWebApplication.php(141): CWebApplication->runController()
#17 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/base/CApplication.php(180): CWebApplication->processRequest()
#18 /Applications/XAMPP/xamppfiles/htdocs/yii-new/testdrive/index-test.php(15): CWebApplication->run()
REQUEST_URI=/yii-new/testdrive/index-test.php?r=tblUser/index
2013/11/17 16:24:57 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CController.php:1118
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/filters/CInlineFilter.php(58): CController->filterPostOnly(Object(CFilterChain))
#1 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#2 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/filters/CFilter.php(40): CFilterChain->run()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CController.php(291): CFilterChain->run()
#7 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CWebApplication.php(282): CController->run('delete')
#9 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CWebApplication.php(141): CWebApplication->runController('word/delete')
#10 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/base/CApplication.php(180): CWebApplication->processRequest()
#11 /Applications/XAMPP/xamppfiles/htdocs/yii-new/testdrive/index-test.php(15): CApplication->run()
#12 {main}
REQUEST_URI=/yii-new/testdrive/index-test.php?r=word/delete&id=2
HTTP_REFERER=http://localhost/yii-new/testdrive/index-test.php?r=word/admin
---
2013/11/23 12:25:27 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CController.php:1118
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/filters/CInlineFilter.php(58): CController->filterPostOnly(Object(CFilterChain))
#1 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#2 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/filters/CFilter.php(40): CFilterChain->run()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CController.php(291): CFilterChain->run()
#7 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CWebApplication.php(282): CController->run('delete')
#9 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CWebApplication.php(141): CWebApplication->runController('word2/delete')
#10 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/base/CApplication.php(180): CWebApplication->processRequest()
#11 /Applications/XAMPP/xamppfiles/htdocs/yii-new/testdrive/index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/yii-new/testdrive/index.php?r=word2/delete&id=1
HTTP_REFERER=http://localhost/yii-new/testdrive/index.php?r=word2/admin
---
2013/11/23 12:28:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "ace".' in /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CWebApplication.php:286
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/web/CWebApplication.php(141): CWebApplication->runController('ace')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii-new/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii-new/testdrive/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii-new/testdrive/index.php?r=ace
---
